folder: Фотокамера
ignore: ignore.list
ignoreDeleted: true
password: mypassword
port: 4000
removeFromCloud: false
target: D:/pathtomy/photos/
timeout: 60
url: https://webdav.yandex.ru
username: mylogin
